name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fonttools brotli

      - name: Install Node.js dependencies
        run: npm ci

      - name: Apply patches
        run: npm run postinstall

      - name: Build Astro site
        run: npm run build

      - name: Subset fonts and replace originals
        run: python scripts/fonts.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: https://wermos.github.io/blog-v3

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.4
